<?php
	$this->addStyle("css/global.css");
	$this->addStyle("css/admin.css");
	$this->addScript("http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<title><?php echo isset($this->title)? $this->title:'No title'; ?></title>
		<?php echo $this->getHeaderIncludes(); ?>
	</head>
	<body>
		<div id="wrapper">
			<div id="header">
				<h2>Administration</h2>
			</div>
			<div id="main_content">
				<div id="main_menu">
					<?php $this->partial('main_menu'); ?>
				</div>
				<?php $this->getContent(); ?>
			</div>
			<div id="footer">
			</div>
		</div>
	</body>
</html>